<a href="https://colab.research.google.com/github/Sudeeppp-Mishra/Machine-Learning-101/blob/main/Lab-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Experiment 1: Introduction to Python Lists


1. Create a list of five subjects.

In [1]:
list = [1, 2, 3, 4, 5]

2. Print the first and last element.

In [3]:
print(f'First element: {list[0]}')
print(f'Last element: {list[-1]}')

First element: 1
Last element: 5


3. Replace teh third subject with another subject.

In [4]:
list[2] = 10
print(f'Updated third subject: {list[2]}')

Updated third subject: 10


## Experiment 2: List Operations and Methods

- append() -> Adds element at end
- insert() -> Inserts element
- remove() -> Remove element
- pop() -> Removes by index
- sort() -> Sorts list
- reverse() -> Reverse list

1. Create a list of integers

In [23]:
list1 = [2, 7, 9, 8, 3, 4, 5, 10, -1]

2. Add two elements using append()

In [24]:
list1.append(13)
list1.append(90)
print(list1)

[2, 7, 9, 8, 3, 4, 5, 10, -1, 13, 90]


3. Remove one element

In [25]:
list1.remove(-1)
print(list1)

[2, 7, 9, 8, 3, 4, 5, 10, 13, 90]


4. Sort the list

In [26]:
list1.sort()
print(list1)

[2, 3, 4, 5, 7, 8, 9, 10, 13, 90]


Descending sort

In [27]:
list1.sort(reverse=True)
print(list1)

[90, 13, 10, 9, 8, 7, 5, 4, 3, 2]


5. Reverse the list

In [28]:
list1.reverse()
print(list1)

[2, 3, 4, 5, 7, 8, 9, 10, 13, 90]


## Experiment 3: Nested Lists and Matrix Operations

1. Create a 3x3 matrix.

In [29]:
matrix3x3 = [[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]]
print(matrix3x3)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


2. Print all diagonal elements

In [30]:
for i in range(len(matrix3x3)):
  print(matrix3x3[i][i])

1
5
9


3. Add two matrices.

In [37]:
matrix3x3_2 = [[3, 5, 5],
               [2, 5 ,7],
               [10, 3, 9]]
matrix3x3_sum = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(matrix3x3)):
  for j in range(len(matrix3x3_2[0])):
    matrix3x3_sum[i][j] = matrix3x3_2[i][j] + matrix3x3[i][j]
print(matrix3x3_sum)

[[4, 7, 8], [6, 10, 13], [17, 11, 18]]


4. Multiply two matrix

In [44]:
matrix3x3_product = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(matrix3x3)):
  for j in range(len(matrix3x3_2[0])):
    for k in range(len(matrix3x3_2)):
      matrix3x3_product[i][j] += matrix3x3[i][k]*matrix3x3_2[k][j]
print(matrix3x3_product)

[[37, 24, 46], [82, 63, 109], [127, 102, 172]]


5. Use 3x4 matrix

In [46]:
matrixA = [[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12]] # 3x4

matrixB = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9],
           [10, 11, 12]] # 4x3

matrix_product = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(matrixA)):
  for j in range(len(matrixB[0])):
    for k in range(len(matrixB)):
      matrix_product[i][j] += matrixA[i][k]*matrixB[k][j];
print(matrix_product)

[[70, 80, 90], [158, 184, 210], [246, 288, 330]]


Multiplying using NumPy

In [48]:
import numpy as np

matrix_product_numpy = np.matmul(matrixA, matrixB)
print(matrix_product_numpy)

[[ 70  80  90]
 [158 184 210]
 [246 288 330]]
